In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# !unzip '/content/tmdb_5000_credits.csv.zip'

In [ ]:
# !unzip '/content/tmdb_5000_movies.csv.zip'

In [ ]:
movies=pd.read_csv('/content/tmdb_5000_movies.csv')
credits=pd.read_csv('/content/tmdb_5000_credits.csv')

In [ ]:
movies.sample(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
2418,0,"[{""id"": 35, ""name"": ""Comedy""}]",NaN,13778,"[{""id"": 3090, ""name"": ""loser""}, {""id"": 5561, ""...",en,Dickie Roberts: Former Child Star,"TV child star of the '70s, Dickie Roberts is n...",10.149569,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2003-09-05,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,50 million people used to watch him on TV. Now...,Dickie Roberts: Former Child Star,5.1,64
2831,12000000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 878, ""na...",NaN,13812,"[{""id"": 6898, ""name"": ""quarantine""}, {""id"": 97...",en,Quarantine,A television reporter and her cameraman are tr...,8.083995,"[{""name"": ""Vertigo Entertainment"", ""id"": 829},...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2008-10-10,40855419,89.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Contain The Truth.,Quarantine,5.5,339
3650,0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",NaN,56930,"[{""id"": 1262, ""name"": ""mountains""}, {""id"": 572...",en,Tycoon,Engineer Johnny Munroe is enlisted to build a ...,0.042442,"[{""name"": ""RKO Radio Pictures"", ""id"": 6}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1947-12-27,0,128.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Breath-taking Adventure !,Tycoon,6.6,4
4158,2000000,"[{""id"": 53, ""name"": ""Thriller""}]",http://www.screenmedia.net/project/shark-lake/,299553,"[{""id"": 1889, ""name"": ""lake""}, {""id"": 2988, ""n...",en,Shark Lake,Meredith Hendricks happens to be the best cop ...,1.187764,"[{""name"": ""FLF Films"", ""id"": 36684}, {""name"": ...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-10-02,0,92.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,In this lake you have to fight to survive,Shark Lake,4.4,19
3022,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,14544,[],en,Roll Bounce,"From Wikipedia, the free encyclopedia. Roll Bo...",2.596338,"[{""name"": ""Fox Searchlight Pictures"", ""id"": 43}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-09-23,0,112.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Roll Bounce,6.1,27

In [ ]:
credits.sample()

,movie_id,title,cast,crew
2288,385383,Fight Valley,"[{""cast_id"": 2, ""character"": ""Duke"", ""credit_i...","[{""credit_id"": ""56ed0e07c3a36822590056b3"", ""de..."

In [ ]:
movies=movies.merge(credits,on='title')

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [ ]:
movies = movies.drop(columns=['budget','homepage','original_language','popularity','production_companies','production_countries','revenue','runtime','spoken_languages','tagline','status','title','vote_average','vote_count','movie_id'])

In [ ]:
movies['year']=pd.to_datetime(movies['release_date']).dt.year

In [ ]:
movies=movies.drop(columns=['release_date'])

In [ ]:
movies.head()

,genres,id,keywords,original_title,overview,cast,crew,year
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009.0
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007.0
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",2015.0
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",2012.0
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",2012.0

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   genres          4809 non-null   object
 1   id              4809 non-null   int64
 2   keywords        4809 non-null   object
 3   original_title  4809 non-null   object
 4   overview        4806 non-null   object
 5   cast            4809 non-null   object
 6   crew            4809 non-null   object
 7   year            4808 non-null   float64
dtypes: float64(1), int64(1), object(6)
memory usage: 338.1+ KB

In [ ]:
movies.isnull().sum()

genres            0
id                0
keywords          0
original_title    0
overview          3
cast              0
crew              0
year              1
dtype: int64

In [ ]:
movies.dropna(how='any',inplace=True)

In [ ]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
def tag(genre):
  lis=[]
  for i in ast.literal_eval(genre):
    lis.append(i["name"])
  return lis

In [ ]:
import ast
movies['genres']=movies['genres'].apply(tag)

In [ ]:
movies['keywords']=movies['keywords'].apply(tag)

In [ ]:
# Extract the names of the first three cast members from the JSON-like string and return them as a list.

def tag1(cast):
  l=[]
  s=1
  for i in ast.literal_eval(cast):
    if s!=4:
       l.append(i["name"])
       s+=1
    else:
      break
  return l

In [ ]:
movies['cast']=movies['cast'].apply(tag1)

In [ ]:
movies.head()

,genres,id,keywords,original_title,overview,cast,crew,year
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009.0
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007.0
2,"[Action, Adventure, Crime]",206647,"[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",2015.0
3,"[Action, Crime, Drama, Thriller]",49026,"[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",2012.0
4,"[Action, Adventure, Science Fiction]",49529,"[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",2012.0

In [ ]:
def director(crew):
  lis=[]
  for i in ast.literal_eval(crew):
    if i["job"]=='Director':
     lis.append(i['name'])
     break
  return lis

In [ ]:
movies['crew']=movies['crew'].apply(director)

In [ ]:
movies.head(1)

,genres,id,keywords,original_title,overview,cast,crew,year
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],2009.0

In [ ]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [ ]:
movies.head(1)

,genres,id,keywords,original_title,overview,cast,crew,year
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],2009.0

In [ ]:
def year(yr):
  l=[]
  l.append(int(yr))
  return l

In [ ]:
def year2(yr):
  l=[]
  l.append(str(yr))
  return l

In [ ]:
movies['year']=movies['year'].apply(year)
movies['year']=movies['year'].apply(year2)

In [ ]:
movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

0           [JamesCameron]
1          [GoreVerbinski]
2              [SamMendes]
3       [ChristopherNolan]
4          [AndrewStanton]
               ...
4804     [RobertRodriguez]
4805         [EdwardBurns]
4806          [ScottSmith]
4807          [DanielHsia]
4808     [BrianHerzlinger]
Name: crew, Length: 4805, dtype: object

In [ ]:
movies['tags']=movies['genres']+movies['cast']+movies['keywords']+movies['crew']+movies['overview']+movies['year']

In [ ]:
movies.head(1)

,genres,id,keywords,original_title,overview,cast,crew,year,tags
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],[[2009]],"[Action, Adventure, Fantasy, Science Fiction, ..."

In [ ]:
movies=movies[['id','original_title','tags']]
movies.head(5)

,id,original_title,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction, ..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, Johnny Depp, Orla..."
2,206647,Spectre,"[Action, Adventure, Crime, Daniel Craig, Chris..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, Christian Bal..."
4,49529,John Carter,"[Action, Adventure, Science Fiction, Taylor Ki..."

In [ ]:
# HERE WE JOIN ALL THE TAGS OF A ROW TO MAKE LIKE A SENTENCE
movies['tags'].apply(lambda x:' '.join(x))

0       Action Adventure Fantasy Science Fiction Sam W...
1       Adventure Fantasy Action Johnny Depp Orlando B...
2       Action Adventure Crime Daniel Craig Christoph ...
3       Action Crime Drama Thriller Christian Bale Mic...
4       Action Adventure Science Fiction Taylor Kitsch...
                              ...
4804    Action Crime Thriller Carlos Gallardo Jaime de...
4805    Comedy Romance Edward Burns Kerry Bishé Marsha...
4806    Comedy Drama Romance TV Movie Eric Mabius Kris...
4807    Daniel Henney Eliza Coupe Bill Paxton Daniel H...
4808    Documentary Drew Barrymore Brian Herzlinger Co...
Name: tags, Length: 4805, dtype: object

In [ ]:
movies['tags']=movies['tags'].apply(lambda x:' '.join(x))

<ipython-input-36-afebb7e20b3e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']=movies['tags'].apply(lambda x:' '.join(x))

In [ ]:
movies.head(1)

      id original_title                                               tags
0  19995         Avatar  Action Adventure Fantasy Science Fiction Sam W...

In [ ]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [ ]:
# Stemming of words into one common word
def stem(words):
  l=[]
  for i in words.split():
    l.append(ps.stem(i))

  return " ".join(l)

In [ ]:
movies['tags']=movies['tags'].apply(stem)

In [ ]:
# Create a CountVectorizer object with specified parameters
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=6000,stop_words='english')

In [ ]:
vec=cv.fit_transform(movies['tags']).toarray()
vec.shape

(4805, 6000)

In [ ]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zooey', 'zucker', 'zwick'], dtype=object)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cs=cosine_similarity(vec)
cs.shape # Get the shape of the cosine similarity matrix

(4805, 4805)

In [ ]:
cs[0]

array([1.        , 0.06429074, 0.06301753, ..., 0.04252433, 0.02954626,
       0.        ])

In [ ]:
pip install fuzzywuzzy

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0

In [ ]:
import fuzzywuzzy
from fuzzywuzzy import process

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [ ]:
# Define a function to recommend movies based on a given movie title
def recomd(movie):
  fuzzed = fuzzywuzzy.process.extractOne(movie,movies['original_title'])
  y=fuzzed[0]
  movi_index=movies[movies['original_title']==y].index[0]
  movi_list=sorted(list(enumerate(cs[movi_index])),reverse=True,key=lambda x:x[1])[1:6]

  for i in movi_list:
    print(movies.iloc[i[0]].original_title)

In [ ]:
recomd('avtr')

Aliens
Silent Running
Moonraker
Alien
Mission to Mars

In [ ]:
import pickle

In [ ]:
pickle.dump(movies,open('movie_model.pkl','wb'))

In [ ]:
pickle.dump(cs,(open('matrix_data.pkl','wb')))